### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Kallmark** [hajame/otm-harjoitustyo#2]
Palaute perustuu ke 3.5 klo 20:30 ladattuun versioon.

Vaikkei koodikatselmoinnissa olisi tarvinnut ottaa kantaa, totean silti, että vaativuusmäärittelyn dokumentointi tehty erinomaisesti ja havainnollistamisessa on esimerkillisesti käytetty myös kuvia. Sovelluksen tarkoitus ja perustoiminnallisuudet selviävät lukijalle helposti. Koodiin tutustuminen oli varsin helppoa, sillä vaativuusmäärittely selvensi hyvin mitä sovellus tekee. Kiitos!

-Sovelluksen pakkausrakenne on mielestäni järkevästi rakennettu eikä siinä ole puutteita. 
-Metodien ja luokkien nimeämisessä on oltu johdonmukainen, esimerkiksi kieli on johdonmukaisesti nimistä Javadociin englanti. Kattavat javadocit helpottivat myös koodiin tutustumista. 
-Muuttujien nimistä käy selkeästi ilmi, mihin ne on tarkoitettu. Esimerkkinä Exercise -luokan Timestamp, avgspeed, distance ja duration -muuttujat. 
-Onko DAO-mallien testaus jätetty tekemättä jostain erityisestä syystä? Samaa pakkausrakennetta ei löytynyt testien osalta, joista tietenkin käyttöliittymä on jätetty pois. Kenties loppuversioon voisi tehdä myös sql-kyselyitä testaavia testejä?
-Pitkiä metodeja Dao-malleissa kuten saveOrUpdate pilkottu useampaan osaan, mikä tekee koodista helposti ymmärettävää ja luettavaa. Kenties javadocissa voisi mainita pilkottujen metodien kohdalla  esimerkiksi “kts. Save() ja update()”?
-Databasen init() ja sqlitecommands() -metodit helpoittaisivat myös sql-kyselyjen mahdollista testausta, sillä testitietokannan voisi aina alustaa testien alkuun. Metodien tekeminen hyvin ajateltu.
-Sovelluslogiikka on eroteltu hyvin, tekee DAO-luokkien käyttämisestä varmasti helpompaa ja käyttöliittymän koodista helpommin ymmärettävää. Kaiken kaikkiaan koodin rakenne ja käyttöliittymän sekä toiminnallisuuksien erottelu toteutettu hyvin. 
-Luokkien vastuualueet ovat niin ikään selkeät ja toteutettu hyvin. Vastuiden jakaminen on toteutettu järkevästi. Dao-luokat hoitavat sql-kyselyt ja Logic-luokka hoitaa kommunikoinnin niiden ja käyttöliittymän välillä. 
-Mahdollisten erroreiden käsittely myös hoidettu hyvin, esimerkkinä logiikka-luokan addExercise-metodin try-catch. Ehkä error-viestin voisi välittää myös käyttäjälle?
-Kaikenkaikkiaan sovellus on mielestäni tehty sillä tapaa, että sen jatkokehittäminen olisi helppoa. Rakenne on niin selkeä, että uusien toiminnallisuuksien lisääminen on luultavasti varsin helppoa. En keksinyt suuria puutteita tai muita parannusehdotuksia kuin edellä mainitut ehdotukset. Sovellus vaikuttaa jo tässä vaiheessa, kuten pitääkin, varsin valmiilta. 

Ilmeisesti seuraavia huomioita ei olisi koodikatselmoinnissa tarvinnut, mutta kokeiltuani sovellusta keksin ainakin kaksi ehdotusta jatkokehitykselle, toivottavasti ne ovat mielestäsi hyödyllisiä:

-Sovellusta käyttäessä data pitää syöttää varsin tarkassa muodossa tai sovellus ei lisää mitään. Käyttohjeissa todetaan hyvin, että näkyvä data toimii malliformaattina. Voisiko kuitenkin itse käyttöliittymässäkin esimerkiksi lisäyskenttien alla olla tekstimuodossa kuhunkin kentän oletettu formaatti? Uuden käyttäjän lisäyksessä olemassaolevaa dataa ei ole joten ,käytettävyys voisi tällöin olla parempi kun malliesmerkkiä ei ole välittömästi käyttäjän edessä.
-Tilastonäkymä on mielenkiintonen ja mielestäni hyvä tapa käyttää ulkoista kirjastoa. Kenties tulevaisuuden jatkokehityksessä tilastot voisivat näkyä myös graafisesti (esimerkiksi kuvaajana matkojen ajat sekä etäisyydet ja niiden kehitys)?

Sovelluksesi vaikuttaa kaikinpuolin hyvältä!

**Comment by hajame** [comment]
Kiitos loistavasta palautteestasi!

- Käyttäjille näkyvät virheilmoitukset väärästä tietoformaatista on todella tarpeellinen ominaisuus, jota aion kehittää jatkossa.

Jatkokehitysidoihisi liittyen:

- Korjasin malliformaatin siten, että ohjelma hakee aina järjestelmän päivän ja kellonajan, sekä oletuksena 30min ja 5.0km lenkin käyttäjälle. Tämän pitäisi ohjata käyttäjä tallentamaan tieto oikeassa formaatissa, eikä käyttäjän useimmiten tarvitse vaihtaa kuin matkan pituus ja kesto, lenkit kun yleensä kirjataan samana päivänä tai ainakin saman kuun aikana. Jos käyttäjä kuitenkin vahingossa poistaa olemassa olevan tekstin, tulee esiin harmaa esimerkkiteksti, joka poistuu kun käyttäjä alkaa kirjoittamaan.
- Tilastotiedon graafinen esittäminen JavaFX:n työkaluja hyödyntäen on jatkosuunnitelmissa loppupalautuksen jälkeen.

Kiitos vielä kerran palautteestasi!
